language: go

dist: focal

notifications:
  email: true

go:
- '1.18.x'
- '1.19.x'
- '1.20.x'

env:
  global:
  - GO111MODULE=on

before_install:
- sudo apt-get update
- sudo apt-get install python
- nvm install --lts
- npm install npm@latest -g

install:
- curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.52.2

script:
- make travis-ci

before_deploy:
- pip install --user bump2version
- npm install @semantic-release/changelog
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/github

deploy:
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    go: '1.18.x'
    branch: master
